version: '3.3'
services:
  dev:
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'   #
      - '${KINDYN_PATH}:/roboy3/src/kindyn'
      - '${ROS2_KINDYN_PATH}:/ros2_roboy3/src/ros2_kindyn'
      - '${ROS2_ROBOY3_MODELS_PATH}:/ros2_roboy3/src/ros2_roboy3_models'
      - '${ROS2_COMMON_UTILITIES_PATH}:/ros2_roboy3/src/ros2_common_utilities'
      - '${ROS2_ROBOY_COMMUNICATION_PATH}:/ros2_roboy3/src/ros2_roboy_communication'
    environment:
      - 'DISPLAY=${DISPLAY}'              # set DISPLAY in .env
    tty: true                             # -t
    stdin_open: true                      # -i
    privileged: true                      # --privileged
    image: ros1-bridge-roboy
    build:
      context: .
      dockerfile: Dockerfile_dev
    command: bash


# xhost local:root 
# docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=${DISPLAY:0} -ti -d ros1-bridge-roboy bash

# docker compose up